# Generated by Django 2.2.8 on 2019-12-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceDetail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='device',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
