# Generated by Django 2.2.8 on 2019-12-18 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deviceDetail', '0002_auto_20191218_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='user',
            new_name='username',
        ),
    ]
