# Generated by Django 2.2.8 on 2019-12-18 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deviceDetail', '0003_auto_20191218_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth0login.Profile'),
        ),
    ]
