# Generated by Django 2.2.8 on 2019-12-18 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deviceDetail', '0004_auto_20191218_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='username',
            new_name='profile',
        ),
    ]
