# Generated by Django 2.2.8 on 2019-12-18 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deviceDetail', '0005_auto_20191218_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='profile',
        ),
        migrations.AddField(
            model_name='device',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
