# Generated by Django 2.2.8 on 2019-12-19 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceDetail', '0006_auto_20191218_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='description',
        ),
        migrations.RemoveField(
            model_name='device',
            name='price',
        ),
        migrations.RemoveField(
            model_name='device',
            name='quantity',
        ),
        migrations.AddField(
            model_name='device',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='device',
            name='parameters',
            field=models.CharField(default='Pass Dictionary here', max_length=1000),
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.CharField(default='Pass List here', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
