# Generated by Django 2.2.8 on 2019-12-19 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceDetail', '0008_auto_20191219_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
