# Generated by Django 2.2.8 on 2019-12-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceDetail', '0009_device_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='parameters',
            field=models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('DECEMBER', 'December')], default='JANUARY', max_length=1000),
        ),
    ]
