# Generated by Django 2.2.8 on 2019-12-16 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=12)),
                ('address', models.CharField(default='', max_length=200)),
                ('profession', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=12)),
                ('state', models.CharField(default='', max_length=12)),
                ('country', models.CharField(default='', max_length=12)),
                ('dob', models.DateField(auto_now_add=True)),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
